title: a awesome start
author: Amey Bhavsar
email: iamamey24@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 this is how the legendary Amey learned github :D
# social links
twitter_username: ameybhavsar24
github_username:  ameybhavsar24

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
